# Background and foreground colors
background = #15191F
foreground = #cdd6f4

# Standard colors
palette = 0=#15191F
palette = 1=#F865A5
palette = 2=#29EDBE
palette = 3=#FFC457
palette = 4=#33AEFF
palette = 5=#AF54FF
palette = 6=#2BE3FC
palette = 7=#cdd6f4

# Bright colors
palette = 8=#61656B
palette = 9=#FF598B
palette = 10=#1FE0A6
palette = 11=#FFB630
palette = 12=#33AEFF
palette = 13=#B467F9
palette = 14=#2BCAFC
palette = 15=#e8e8ff
