$color = rgba(21, 25, 31, 1)
$inner_color = rgba(21, 25, 31, 0.66)
$outer_color = rgba(175, 84, 255, 1)
$font_color = rgba(205, 214, 244, 1)
$placeholder_color = rgba(205, 214, 244, 0.7)
$check_color = rgba(43, 227, 252, 1)
