background            #15191F
foreground            #cdd6f4

# black
color0  #15191F
color8  #61656B

# red
color1  #F865A5
color9  #FF598B

# green
color2  #29EDBE
color10 #1FE0A6

# yellow
color3  #FFC457
color11 #FFB630

# blue
color4  #33AEFF
color12 #33AEFF

# magenta
color5  #AF54FF
color13 #B467F9

#cyan
color6  #2BE3FC
color14 #2BCAFC

#white
color7  #cdd6f4
color15 #e8e8ff


